# get settings /api/settings 
GET http://localhost:4040/settings

### update settings /api/settings/id
PATCH  http://localhost:4040/settings/beecd0a5-24ab-4c4a-9977-acbb4e92ef96
Content-Type: application/json

{
    "data": {
        "clientSatisfaction": 100
    }
}


### get all socials /api/settings/socials - should be restricted and not have caching
GET http://localhost:4040/settings/socials


### get all projects /api/settings/projects - should be restricted and not have caching
GET http://localhost:4040/settings/projects


### get all testimonials /api/settings/testimonials - should be restricted and not have caching
GET http://localhost:4040/settings/testimonials


### get all tools /api/settings/tools - should be restricted and not have caching
GET http://localhost:4040/settings/tools



### add social - should be restricted
POST http://localhost:4040/settings/socials
Content-Type: application/json

{
    "data": {
        "name": "social x",
        "link": "https://x234.com",
        "icon": "bx bxs-user-x",
        "dddd": "ddd"

    }
}


### add project - should be restricted
POST http://localhost:4040/settings/projects
Content-Type: application/json

{
    "data": {
        "name": "new project by same client",
        "services": ["1", "2", "3"],
        "images": [
            "https://picsum.photos/1440/800",
            "https://picsum.photos/1440/800",
            "https://picsum.photos/1440/800"
        ],
        "description": "x  x x x x xx x x x x x xx  x x x ",
        "type": "personal",
        "public": true,
        "clientInfo": {
            "name": "another client",
            "sector": "alagbafo"
        }
    }
}

### add testimonial - should be restricted
POST http://localhost:4040/settings/testimonials
Content-Type: application/json

{
    "data": {
        "rating": 5,
        "comment": "cccc",
        "clientInfo": {
            "name": "agba client",
            "sector": "agba sector",
            "company": "another company"
        }
    }
}

### add tool - should be restricted
POST http://localhost:4040/settings/tools
Content-Type: application/json

{
    "data": {
        "name": "tool x",
        "use": "for x",
        "icon": "bx bxs-user-x"
    }
}



### update social - should be restricted
PATCH http://localhost:4040/settings/socials/9883bc70-cf6b-433e-a0fb-f2b76b99a117
Content-Type: application/json

{
    "data": {
        "name": "updated social x",
        "link": "https://abazus.com"
       
    }
}


### update project - should be restricted
PATCH http://localhost:4040/settings/projects/88c6077b-93c3-4935-9fea-925408a1f2ca
Content-Type: application/json

{
    "data": {
        "services": ["fish", "clean", "wash"]
    }
}




### update testimonial - should be restricted
PATCH http://localhost:4040/settings/testimonials/77893077-e98a-47f9-a213-38c87ea9c11f
Content-Type: application/json

{
    "data": {
        "rating": 3,
        "comment": "this is clean, this is what i mean"
    }
}




### update tool - should be restricted
PATCH http://localhost:4040/settings/tools/0c2eec97-cc3d-4aec-99dc-ba4b60d29864
Content-Type: application/json

{
    "data": {
        "use": "for yxxxx"
    }
}


### delete social - should be restricted
DELETE http://localhost:4040/settings/socials/6bfed573-d41f-4474-90bd-9b6f86d95c5b


### delete project - should be restricted
DELETE http://localhost:4040/settings/projects/89ed3f99-bd28-442f-ab14-546b6e5b0e85


### delete testimonial - should be restricted
DELETE http://localhost:4040/settings/testimonials/776a3a3a-02c4-44f7-b63c-073f44e3d8b3


### delete tool - should be restricted
DELETE http://localhost:4040/settings/tools/0c2eec97-cc3d-4aec-99dc-ba4b60d29864